# Generated by Django 5.0.4 on 2024-05-23 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 23, 8, 35, 47, 474714, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="slug",
                max_length=150,
                null=True,
                verbose_name="slug",
            ),
        ),
    ]
