# Generated by Django 4.2.2 on 2024-06-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0018_alter_article_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
    ]
