# Generated by Django 5.0.4 on 2024-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя контакта",
                        max_length=50,
                        verbose_name="Имя контакта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите телефон контакта",
                        max_length=20,
                        verbose_name="Телефон контакта",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Введите сообщение котакта",
                        null=True,
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "time",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату создания",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
