# Generated by Django 5.0.4 on 2024-05-22 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_contact_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Введите сообщение контакта",
                null=True,
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 5, 22, 19, 6, 9, 94132),
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
    ]
