# Generated by Django 5.0.4 on 2024-05-22 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_contact_time_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 22, 21, 48, 7, 811851, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 22, 21, 48, 7, 811208, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 22, 21, 48, 7, 811234, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату изменения",
                null=True,
                verbose_name="Дата изменения",
            ),
        ),
    ]
