# Generated by Django 5.0.4 on 2024-06-04 13:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_contact_time_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 4, 13, 24, 15, 98603, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 4, 13, 24, 15, 97827, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 4, 13, 24, 15, 97861, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату изменения",
                null=True,
                verbose_name="Дата изменения",
            ),
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="укажите номер версии", verbose_name="Номер версии"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название версии",
                        max_length=100,
                        verbose_name="Название версии",
                    ),
                ),
                ("sign", models.BooleanField(verbose_name="Признак текущей версии")),
                (
                    "product",
                    models.ForeignKey(
                        help_text="название продукта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["number", "name"],
            },
        ),
    ]
