# Generated by Django 4.2.2 on 2024-06-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="d_user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
    ]
